application: statusbotnet
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /static
  static_dir: static
- url: .*
  script: main.application
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
